{
 "title": "Synapse Live Performance",
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Uptime Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{job='synapse-core-app'}" }
   ]
  },
  {
   "title": "HTTP Request Volume (Rate / sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{handler!='/metrics'}[1m])) by (handler)) or vector(0)"
    }
   ]
  },
  {
   "title": "Security Anomalies Detector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(sum(rate(synapse_security_anomalies_total[1m])) by (handler)) or vector(0)"
    }
   ]
  }
 ]
}